[package]
name = "vampire-rpg"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
hecs = "0.10"
thiserror = "1.0"
anyhow = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
